name: pymlir

channels:
- conda-forge

dependencies:
# dev environment
  - python=3.8
  - coverage
  - pytest
  - pytest-cov

# dependencies (so setup.py develop doesn't pip install them)
  - lark-parser
  - parse
